/**
 * Deterministic seed data for the LocalRepository and as a reference for
 * `supabase/seed.sql`. Ids are stable, human-readable slugs so relationships
 * are easy to follow while developing.
 */

import type { DbSnapshot } from "./store";
import { xpForLevel, levelForXp } from "@/lib/app/leveling";

const now = "2026-06-01T12:00:00.000Z";

function profileFor(userId: string, xp: number, points: number, city: string) {
  return {
    user_id: userId,
    home_city: city,
    xp,
    level: levelForXp(xp),
    points_balance_cache: points,
    lifetime_points: points,
    completed_quests_count: 0,
    community_notes_count: 0,
    rewards_redeemed_count: 0,
  };
}

export function buildSeed(): DbSnapshot {
  return {
    users: [
      {
        id: "user-demo",
        email: "quester@sidequests.io",
        display_name: "Quester",
        avatar_url: null,
        role: "user",
        created_at: now,
        last_active_at: now,
        account_status: "active",
      },
      {
        id: "user-mia",
        email: "mia@example.com",
        display_name: "mia_quester",
        avatar_url: null,
        role: "user",
        created_at: now,
        last_active_at: now,
        account_status: "active",
      },
      {
        id: "user-jordan",
        email: "jordan@example.com",
        display_name: "traveljordan",
        avatar_url: null,
        role: "user",
        created_at: now,
        last_active_at: now,
        account_status: "active",
      },
      {
        id: "user-partner",
        email: "partner@wynwood.example",
        display_name: "Wynwood Partner",
        avatar_url: null,
        role: "partner",
        created_at: now,
        last_active_at: now,
        account_status: "active",
      },
      {
        id: "user-admin",
        email: "admin@sidequests.io",
        display_name: "SideQuests Admin",
        avatar_url: null,
        role: "admin",
        created_at: now,
        last_active_at: now,
        account_status: "active",
      },
    ],

    profiles: [
      { ...profileFor("user-demo", xpForLevel(12) + 240, 2500, "Miami, FL"), completed_quests_count: 24, community_notes_count: 3, rewards_redeemed_count: 1 },
      { ...profileFor("user-mia", 8200, 4100, "Miami, FL"), completed_quests_count: 41 },
      { ...profileFor("user-jordan", 6400, 3050, "Miami, FL"), completed_quests_count: 33 },
      profileFor("user-partner", 0, 0, "Miami, FL"),
      profileFor("user-admin", 0, 0, "Miami, FL"),
    ],

    privacy: [
      defaultPrivacy("user-demo"),
      defaultPrivacy("user-mia"),
      defaultPrivacy("user-jordan"),
      defaultPrivacy("user-partner"),
      defaultPrivacy("user-admin"),
    ],

    partners: [
      {
        id: "partner-wynwood",
        name: "Wynwood Arts District",
        type: "venue",
        contact_email: "partner@wynwood.example",
        status: "active",
        owner_user_id: "user-partner",
        created_at: now,
      },
      {
        id: "partner-vice",
        name: "Vice City Coffee Co.",
        type: "brand",
        contact_email: "hello@vicecity.example",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      // Wynwood small businesses
      {
        id: "partner-kyu",
        name: "KYU Miami",
        type: "venue",
        contact_email: "hello@kyurestaurants.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-panther",
        name: "Panther Coffee",
        type: "brand",
        contact_email: "hello@panthercoffee.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-boxelder",
        name: "Boxelder Craft Beer Market",
        type: "venue",
        contact_email: "hello@boxelderbar.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-gramps",
        name: "Gramps",
        type: "venue",
        contact_email: "hello@gramps.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-coyo",
        name: "Coyo Taco",
        type: "venue",
        contact_email: "hello@coyotaco.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-wood",
        name: "Wood Tavern",
        type: "venue",
        contact_email: "hello@woodtavern.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      // Museums & landmarks
      {
        id: "partner-pamm",
        name: "Pérez Art Museum Miami",
        type: "nonprofit",
        contact_email: "info@pamm.org",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-frost",
        name: "Frost Science Museum",
        type: "nonprofit",
        contact_email: "info@frostscience.org",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-vizcaya",
        name: "Vizcaya Museum & Gardens",
        type: "nonprofit",
        contact_email: "info@vizcaya.org",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-bass",
        name: "Bass Museum of Art",
        type: "nonprofit",
        contact_email: "info@bassmuseum.org",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-artdeco",
        name: "Art Deco Historic District",
        type: "nonprofit",
        contact_email: "info@mdpl.org",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
      {
        id: "partner-brickell",
        name: "Brickell Key",
        type: "other",
        contact_email: "info@brickell.com",
        status: "active",
        owner_user_id: null,
        created_at: now,
      },
    ],

    venues: [
      {
        id: "venue-walls",
        partner_id: "partner-wynwood",
        name: "Wynwood Walls",
        address: "2516 NW 2nd Ave",
        city: "Miami, FL",
        latitude: 25.8011,
        longitude: -80.1994,
        status: "active",
      },
      {
        id: "venue-beans",
        partner_id: "partner-vice",
        name: "Vice City Beans",
        address: "120 Collins Ave",
        city: "Miami, FL",
        latitude: 25.7825,
        longitude: -80.1303,
        status: "active",
      },
      {
        id: "venue-pointe",
        partner_id: "partner-wynwood",
        name: "South Pointe Park",
        address: "1 Washington Ave",
        city: "Miami, FL",
        latitude: 25.7617,
        longitude: -80.1308,
        status: "active",
      },
      // Wynwood
      {
        id: "venue-kyu",
        partner_id: "partner-kyu",
        name: "KYU Miami",
        address: "251 NW 25th St",
        city: "Miami, FL",
        latitude: 25.8042,
        longitude: -80.1982,
        status: "active",
      },
      {
        id: "venue-panther",
        partner_id: "partner-panther",
        name: "Panther Coffee Wynwood",
        address: "2390 NW 2nd Ave",
        city: "Miami, FL",
        latitude: 25.8002,
        longitude: -80.1982,
        status: "active",
      },
      {
        id: "venue-boxelder",
        partner_id: "partner-boxelder",
        name: "Boxelder Craft Beer Market",
        address: "2817 NW 2nd Ave",
        city: "Miami, FL",
        latitude: 25.8074,
        longitude: -80.1985,
        status: "active",
      },
      {
        id: "venue-gramps",
        partner_id: "partner-gramps",
        name: "Gramps",
        address: "176 NW 24th St",
        city: "Miami, FL",
        latitude: 25.8027,
        longitude: -80.1997,
        status: "active",
      },
      {
        id: "venue-coyo",
        partner_id: "partner-coyo",
        name: "Coyo Taco Wynwood",
        address: "2300 NW 2nd Ave",
        city: "Miami, FL",
        latitude: 25.8008,
        longitude: -80.1983,
        status: "active",
      },
      {
        id: "venue-wood",
        partner_id: "partner-wood",
        name: "Wood Tavern",
        address: "2531 NW 2nd Ave",
        city: "Miami, FL",
        latitude: 25.8044,
        longitude: -80.1984,
        status: "active",
      },
      // Museums & landmarks
      {
        id: "venue-pamm",
        partner_id: "partner-pamm",
        name: "Pérez Art Museum Miami",
        address: "1103 Biscayne Blvd",
        city: "Miami, FL",
        latitude: 25.7737,
        longitude: -80.1865,
        status: "active",
      },
      {
        id: "venue-frost",
        partner_id: "partner-frost",
        name: "Frost Science Museum",
        address: "1101 Biscayne Blvd",
        city: "Miami, FL",
        latitude: 25.7730,
        longitude: -80.1875,
        status: "active",
      },
      {
        id: "venue-vizcaya",
        partner_id: "partner-vizcaya",
        name: "Vizcaya Museum & Gardens",
        address: "3251 S Miami Ave",
        city: "Miami, FL",
        latitude: 25.7442,
        longitude: -80.2099,
        status: "active",
      },
      {
        id: "venue-bass",
        partner_id: "partner-bass",
        name: "Bass Museum of Art",
        address: "2100 Collins Ave",
        city: "Miami Beach, FL",
        latitude: 25.7930,
        longitude: -80.1305,
        status: "active",
      },
      {
        id: "venue-artdeco",
        partner_id: "partner-artdeco",
        name: "Ocean Drive Art Deco Strip",
        address: "Ocean Drive",
        city: "Miami Beach, FL",
        latitude: 25.7836,
        longitude: -80.1301,
        status: "active",
      },
      {
        id: "venue-brickell-key",
        partner_id: "partner-brickell",
        name: "Brickell Key Park",
        address: "900 Brickell Key Dr",
        city: "Miami, FL",
        latitude: 25.7642,
        longitude: -80.1868,
        status: "active",
      },
    ],

    quests: [
      {
        id: "de000000-0000-0000-0000-000000000001",
        partner_id: "partner-wynwood",
        venue_id: "venue-walls",
        title: "Wynwood Walls",
        description:
          "Explore iconic street art & leave your mark. Find the hidden mural behind the main wall and scan the code to check in.",
        category: "art",
        difficulty: "easy",
        xp_reward: 50,
        points_reward: 100,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url:
          "https://images.unsplash.com/photo-1569700296499-d5671c74cb3d?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Stand in front of your favorite piece and say 'I feel seen' with complete sincerity",
        action_type: "social",
        proof_method: "camera",
        social_share_prompt: "Just stood in front of my favorite mural at Wynwood Walls and said 'I feel seen' 🎨 #SideQuests #WynwoodWalls #Miami",
        estimated_time: "5 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000008",
        partner_id: "partner-vice",
        venue_id: "venue-beans",
        title: "Vice City Beans",
        description:
          "Find the secret menu item and check in. Ask the barista for the passphrase and enter the venue code.",
        category: "food",
        difficulty: "medium",
        xp_reward: 40,
        points_reward: 80,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "venue_code",
        verification_secret: "SUNRISE",
        image_url:
          "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Describe the coffee's flavor to the barista using only geography ('tastes like altitude')",
        action_type: "taste",
        staff_phrase: "SUNRISE",
        proof_method: "staff_phrase",
        social_share_prompt: "Ordered coffee at Vice City Beans and described it using only geography ☕ #SideQuests #ViceCityBeans #Miami",
        estimated_time: "5 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000009",
        partner_id: "partner-wynwood",
        venue_id: "venue-pointe",
        title: "Sunset Chase",
        description:
          "Catch the sunset and leave a Community Note. Check in at South Pointe Park before dusk.",
        category: "outdoors",
        difficulty: "easy",
        xp_reward: 60,
        points_reward: 120,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "gps",
        verification_secret: null,
        image_url:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Spread your arms out wide when you reach the park and face the horizon",
        action_type: "explore",
        proof_method: "camera",
        social_share_prompt: "Arms out wide at South Pointe Park, soaking in the Miami sunset 🌅 #SideQuests #SouthPointe #Miami",
        estimated_time: "2 min",
      },

      // ── Wynwood small businesses ───────────────────────────────────────
      {
        id: "de000000-0000-0000-0000-000000000003",
        partner_id: "partner-kyu",
        venue_id: "venue-kyu",
        title: "KYU: Art of the Binchotan",
        description: "KYU's wood-fired kitchen is a Wynwood institution. Ask your server for the chef's most underrated dish, order it, and enter the code to unlock your reward.",
        category: "food",
        difficulty: "medium",
        xp_reward: 100,
        points_reward: 200,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "venue_code",
        verification_secret: "BINCHO",
        image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Ask the chef for their most underrated dish — then actually order it",
        action_type: "taste",
        staff_phrase: "BINCHO",
        proof_method: "staff_phrase",
        social_share_prompt: "Ordered the chef's secret pick at KYU Miami and it was absolutely fire 🔥 #SideQuests #KYUMiami #Wynwood",
        estimated_time: "10 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000002",
        partner_id: "partner-panther",
        venue_id: "venue-panther",
        title: "Panther Coffee: Single-Origin Ritual",
        description: "Order the house cortadito at Panther Coffee and log the bean's origin country. Ask for the secret pour-over passphrase to complete the quest.",
        category: "food",
        difficulty: "easy",
        xp_reward: 100,
        points_reward: 150,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "venue_code",
        verification_secret: "CORTADO",
        image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Describe the coffee's flavor to the barista using only geography ('tastes like altitude')",
        action_type: "taste",
        staff_phrase: "CORTADO",
        proof_method: "staff_phrase",
        social_share_prompt: "Described my Panther Coffee order using only geography and honestly... it worked ☕ #SideQuests #PantherCoffee #Wynwood",
        estimated_time: "5 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000005",
        partner_id: "partner-boxelder",
        venue_id: "venue-boxelder",
        title: "Boxelder: The Tap Room Ritual",
        description: "Boxelder has one of Miami's best tap lists. Find the logo sign, complete the ritual, then scan to log your visit.",
        category: "nightlife",
        difficulty: "easy",
        xp_reward: 120,
        points_reward: 180,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Clink your glass against the brewery's logo sign before your first sip",
        action_type: "social",
        proof_method: "camera",
        social_share_prompt: "Clinked my glass against the Boxelder sign before my first sip 🍺 #SideQuests #Boxelder #Wynwood",
        estimated_time: "5 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000006",
        partner_id: "partner-gramps",
        venue_id: "venue-gramps",
        title: "Gramps: Backyard Frequency",
        description: "Gramps is Wynwood's living room — part dive bar, part outdoor venue. Find the beat, feel it for 30 seconds, then scan in.",
        category: "nightlife",
        difficulty: "easy",
        xp_reward: 120,
        points_reward: 180,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Nod your head to the beat for 30 solid seconds before logging the genre",
        action_type: "social",
        proof_method: "manual",
        social_share_prompt: "Nodded to the beat at Gramps for 30 whole seconds and I'm not ashamed 🎵 #SideQuests #Gramps #Wynwood",
        estimated_time: "1 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000004",
        partner_id: "partner-coyo",
        venue_id: "venue-coyo",
        title: "Coyo Taco: Spice Declaration",
        description: "At Coyo Taco you have to commit. Before you order, declare your spice level to the table — then stick with it. Scan in at the register.",
        category: "food",
        difficulty: "easy",
        xp_reward: 100,
        points_reward: 150,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Announce your spice level to the table before ordering — no take-backs",
        action_type: "social",
        proof_method: "manual",
        social_share_prompt: "Announced my spice level at Coyo Taco and held my ground 🌶️ #SideQuests #CoyoTaco #Wynwood",
        estimated_time: "2 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000007",
        partner_id: "partner-wood",
        venue_id: "venue-wood",
        title: "Wood Tavern: Terroir Hours",
        description: "Wood Tavern's natural wine list is quietly one of Wynwood's best. Pick a glass, swirl it, and deliver your verdict.",
        category: "nightlife",
        difficulty: "easy",
        xp_reward: 120,
        points_reward: 180,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Swirl your natural wine and say 'it's giving terroir' whether you know what that means or not",
        action_type: "taste",
        proof_method: "manual",
        social_share_prompt: "Said 'it's giving terroir' at Wood Tavern and honestly I was right 🍷 #SideQuests #WoodTavern #Wynwood",
        estimated_time: "2 min",
      },
      // ── Museums & landmarks ────────────────────────────────────────────
      {
        id: "de000000-0000-0000-0000-000000000011",
        partner_id: "partner-pamm",
        venue_id: "venue-pamm",
        title: "PAMM: 60 Seconds with a Masterpiece",
        description: "Pérez Art Museum Miami hangs over Biscayne Bay and holds some of the hemisphere's most vital contemporary work. Find your piece and give it a full minute.",
        category: "culture",
        difficulty: "medium",
        xp_reward: 130,
        points_reward: 250,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Stand in front of the painting for 60 seconds without looking at your phone",
        action_type: "art",
        proof_method: "manual",
        social_share_prompt: "Stood in front of a painting at PAMM for 60 full seconds. No phone. Just vibes 🎨 #SideQuests #PAMM #Miami",
        estimated_time: "1 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000012",
        partner_id: "partner-frost",
        venue_id: "venue-frost",
        title: "Frost Science: Deep Sea Portal",
        description: "Frost Science's five-story aquarium is one of the largest in the world. Find the main tank, press your hand to the glass, and count to five.",
        category: "culture",
        difficulty: "easy",
        xp_reward: 130,
        points_reward: 220,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Press your hand flat on the tank glass and count to five",
        action_type: "explore",
        proof_method: "camera",
        social_share_prompt: "Put my hand on the Frost Science aquarium glass and the fish looked back at me 🐟 #SideQuests #FrostScience #Miami",
        estimated_time: "2 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000013",
        partner_id: "partner-vizcaya",
        venue_id: "venue-vizcaya",
        title: "Vizcaya: Salute the Stone Barge",
        description: "Built in 1916, Vizcaya's stone barge juts into Biscayne Bay like a frozen ship. Pay your respects before you photograph it.",
        category: "culture",
        difficulty: "medium",
        xp_reward: 130,
        points_reward: 230,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Salute the stone barge before you photograph it",
        action_type: "explore",
        proof_method: "camera",
        social_share_prompt: "Saluted the stone barge at Vizcaya like the sea captain I was born to be ⛵ #SideQuests #Vizcaya #Miami",
        estimated_time: "3 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000014",
        partner_id: "partner-bass",
        venue_id: "venue-bass",
        title: "Bass Museum: Provocation Hunt",
        description: "The Bass on Collins Ave has been challenging Miami Beach since 1964. Walk the galleries until you find the piece that makes you react — then react.",
        category: "culture",
        difficulty: "medium",
        xp_reward: 130,
        points_reward: 220,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "qr",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Gasp audibly when you find the most provocative piece",
        action_type: "art",
        proof_method: "manual",
        social_share_prompt: "Gasped audibly at the Bass Museum and I have zero regrets 😮 #SideQuests #BassMuseum #MiamiBeach",
        estimated_time: "15 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000010",
        partner_id: "partner-artdeco",
        venue_id: "venue-artdeco",
        title: "Ocean Drive: Art Deco Sizing",
        description: "Ocean Drive is the world's most celebrated Art Deco mile. Stand at one end and take it all in before you sit anywhere.",
        category: "culture",
        difficulty: "easy",
        xp_reward: 110,
        points_reward: 180,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "gps",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Look up and down Ocean Drive slowly before you sit, like you're sizing it up",
        action_type: "explore",
        proof_method: "camera",
        social_share_prompt: "Sizing up Ocean Drive like I own it 🌴 #SideQuests #ArtDeco #SouthBeach #Miami",
        estimated_time: "5 min",
      },
      {
        id: "de000000-0000-0000-0000-000000000015",
        partner_id: "partner-brickell",
        venue_id: "venue-brickell-key",
        title: "Brickell Key: The Skyline Claim",
        description: "Brickell Key is a man-made island with unobstructed views of one of the fastest-growing skylines in America. Walk to the waterfront and claim it.",
        category: "outdoors",
        difficulty: "easy",
        xp_reward: 115,
        points_reward: 180,
        status: "active",
        start_date: null,
        end_date: null,
        verification_type: "gps",
        verification_secret: null,
        image_url: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&h=600&fit=crop",
        created_at: now,
        funky_action: "Point dramatically at the Miami skyline and say 'that's mine'",
        action_type: "social",
        proof_method: "camera",
        social_share_prompt: "Pointed at the Miami skyline and said 'that's mine' with full conviction 🏙️ #SideQuests #BrickellKey #Miami",
        estimated_time: "2 min",
      },
    ],

    qrCodes: [
      {
        id: "qr-wynwood",
        quest_id: "de000000-0000-0000-0000-000000000001",
        venue_id: "venue-walls",
        partner_id: "partner-wynwood",
        code: "WYNWOOD1",
        destination_url: "/q/de000000-0000-0000-0000-000000000001",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-beans",
        quest_id: "de000000-0000-0000-0000-000000000008",
        venue_id: "venue-beans",
        partner_id: "partner-vice",
        code: "BEANS1",
        destination_url: "/q/de000000-0000-0000-0000-000000000008",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-sunset",
        quest_id: "de000000-0000-0000-0000-000000000009",
        venue_id: "venue-pointe",
        partner_id: "partner-wynwood",
        code: "SUNSET1",
        destination_url: "/q/de000000-0000-0000-0000-000000000009",
        status: "active",
        created_at: now,
      },
      // Wynwood
      {
        id: "qr-kyu",
        quest_id: "de000000-0000-0000-0000-000000000003",
        venue_id: "venue-kyu",
        partner_id: "partner-kyu",
        code: "KYU1",
        destination_url: "/q/de000000-0000-0000-0000-000000000003",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-panther",
        quest_id: "de000000-0000-0000-0000-000000000002",
        venue_id: "venue-panther",
        partner_id: "partner-panther",
        code: "PANTHER1",
        destination_url: "/q/de000000-0000-0000-0000-000000000002",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-boxelder",
        quest_id: "de000000-0000-0000-0000-000000000005",
        venue_id: "venue-boxelder",
        partner_id: "partner-boxelder",
        code: "BOXELDER1",
        destination_url: "/q/de000000-0000-0000-0000-000000000005",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-gramps",
        quest_id: "de000000-0000-0000-0000-000000000006",
        venue_id: "venue-gramps",
        partner_id: "partner-gramps",
        code: "GRAMPS1",
        destination_url: "/q/de000000-0000-0000-0000-000000000006",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-coyo",
        quest_id: "de000000-0000-0000-0000-000000000004",
        venue_id: "venue-coyo",
        partner_id: "partner-coyo",
        code: "COYO1",
        destination_url: "/q/de000000-0000-0000-0000-000000000004",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-wood-tavern",
        quest_id: "de000000-0000-0000-0000-000000000007",
        venue_id: "venue-wood",
        partner_id: "partner-wood",
        code: "WOOD1",
        destination_url: "/q/de000000-0000-0000-0000-000000000007",
        status: "active",
        created_at: now,
      },
      // Museums & landmarks
      {
        id: "qr-pamm",
        quest_id: "de000000-0000-0000-0000-000000000011",
        venue_id: "venue-pamm",
        partner_id: "partner-pamm",
        code: "PAMM1",
        destination_url: "/q/de000000-0000-0000-0000-000000000011",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-frost",
        quest_id: "de000000-0000-0000-0000-000000000012",
        venue_id: "venue-frost",
        partner_id: "partner-frost",
        code: "FROST1",
        destination_url: "/q/de000000-0000-0000-0000-000000000012",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-vizcaya",
        quest_id: "de000000-0000-0000-0000-000000000013",
        venue_id: "venue-vizcaya",
        partner_id: "partner-vizcaya",
        code: "VIZCAYA1",
        destination_url: "/q/de000000-0000-0000-0000-000000000013",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-bass",
        quest_id: "de000000-0000-0000-0000-000000000014",
        venue_id: "venue-bass",
        partner_id: "partner-bass",
        code: "BASS1",
        destination_url: "/q/de000000-0000-0000-0000-000000000014",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-art-deco",
        quest_id: "de000000-0000-0000-0000-000000000010",
        venue_id: "venue-artdeco",
        partner_id: "partner-artdeco",
        code: "ARTDECO1",
        destination_url: "/q/de000000-0000-0000-0000-000000000010",
        status: "active",
        created_at: now,
      },
      {
        id: "qr-brickell-key",
        quest_id: "de000000-0000-0000-0000-000000000015",
        venue_id: "venue-brickell-key",
        partner_id: "partner-brickell",
        code: "BRICKELL1",
        destination_url: "/q/de000000-0000-0000-0000-000000000015",
        status: "active",
        created_at: now,
      },
    ],

    rewards: [
      {
        id: "reward-coffee",
        partner_id: "partner-vice",
        title: "Free Cold Brew",
        description: "Redeem for one free cold brew at Vice City Beans.",
        points_cost: 500,
        inventory: 50,
        status: "active",
        expiration_date: null,
        image_url:
          "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop",
      },
      {
        id: "reward-print",
        partner_id: "partner-wynwood",
        title: "Limited Art Print",
        description: "A signed Wynwood Walls art print from a featured artist.",
        points_cost: 1500,
        inventory: 10,
        status: "active",
        expiration_date: null,
        image_url:
          "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=600&h=400&fit=crop",
      },
      {
        id: "reward-tour",
        partner_id: "partner-wynwood",
        title: "VIP Gallery Tour",
        description: "Skip-the-line VIP guided tour of the Wynwood galleries.",
        points_cost: 2500,
        inventory: 5,
        status: "active",
        expiration_date: null,
        image_url:
          "https://images.unsplash.com/photo-1577720580479-7d839d829c73?w=600&h=400&fit=crop",
      },
    ],

    notes: [
      {
        id: "note-1",
        user_id: "user-mia",
        quest_id: "de000000-0000-0000-0000-000000000009",
        venue_id: "venue-pointe",
        content:
          "Sunset was unreal tonight 🌅 Bring a blanket and good company.",
        image_url:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=200&h=200&fit=crop",
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-2",
        user_id: "user-jordan",
        quest_id: "de000000-0000-0000-0000-000000000001",
        venue_id: "venue-walls",
        content: "Hidden spot behind the main wall is a must-see!",
        image_url:
          "https://images.unsplash.com/photo-1569700296499-d5671c74cb3d?w=200&h=200&fit=crop",
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-3",
        user_id: "user-mia",
        quest_id: "de000000-0000-0000-0000-000000000003",
        venue_id: "venue-kyu",
        content: "Asked for the underrated dish and they brought out the wood-roasted cauliflower. I didn't expect to be changed by a vegetable.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-4",
        user_id: "user-jordan",
        quest_id: "de000000-0000-0000-0000-000000000002",
        venue_id: "venue-panther",
        content: "Told the barista the coffee tasted like 'early morning in a coastal town' and they wrote it down on the chalkboard.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-5",
        user_id: "user-mia",
        quest_id: "de000000-0000-0000-0000-000000000011",
        venue_id: "venue-pamm",
        content: "60 seconds in front of the Teresita Fernández piece. I lost count. Stayed 3 minutes. 10/10 quest.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-6",
        user_id: "user-jordan",
        quest_id: "de000000-0000-0000-0000-000000000013",
        venue_id: "venue-vizcaya",
        content: "Snapped the most unhinged formal salute photo of my life in front of the stone barge. The tourists nearby were confused. I was not.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-7",
        user_id: "user-mia",
        quest_id: "de000000-0000-0000-0000-000000000015",
        venue_id: "venue-brickell-key",
        content: "Said 'that's mine' pointing at the entire Miami skyline. Two runners nearby clapped. Best day.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-8",
        user_id: "user-jordan",
        quest_id: "de000000-0000-0000-0000-000000000012",
        venue_id: "venue-frost",
        content: "The hammerhead shark swam right toward my hand on the glass. I stayed completely still. It's a spiritual experience.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
      {
        id: "note-9",
        user_id: "user-mia",
        quest_id: "de000000-0000-0000-0000-000000000006",
        venue_id: "venue-gramps",
        content: "Got to 30 seconds, identified the genre as 'cosmic cumbia', and nobody corrected me.",
        image_url: null,
        moderation_status: "approved",
        created_at: now,
      },
    ],

    ledger: [],
    attempts: [],
    completions: [],
    redemptions: [],
    scans: [],
    consents: [],
    audit: [],
  };
}

function defaultPrivacy(userId: string) {
  return {
    user_id: userId,
    analytics_consent: true,
    marketing_consent: false,
    location_consent: false,
    leaderboard_visibility: "public" as const,
    profile_visibility: "public" as const,
  };
}
